name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      previous_run_id:
        description: 'Enter the previous run ID'
        required: true

jobs:
  run_script:
    runs-on: ubuntu-latest

    services:
      ngrok:
        image: ghcr.io/kubesail/unprivileged-ngrok:latest
        ports:
          - 5000:5000  # Expose port 5000

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # If you have any dependencies

    - name: Install ngrok
      run: |
        sudo apt update && sudo apt install ngrok

    - name: Authenticate ngrok
      run: ngrok authtoken ${{ secrets.NGROK_TOKEN }}

    - name: Start ngrok
      run: ngrok http 5000 &
      env:
        NGROK_PORT: 5000

    - name: Run script.py
      run: python script.py
      env:
        CURRENT_RUN_ID: ${{ github.run_id }}
        PREVIOUS_RUN_ID: ${{ github.event.inputs.previous_run_id }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NGROK_PORT: 5000
