name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      previous_run_id:
        description: 'Enter the previous run ID'
        required: true

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # If you have any dependencies

    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
          sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
          sudo tee /etc/apt/sources.list.d/ngrok.list && \
          sudo apt update && sudo apt install ngrok

    - name: Authenticate ngrok
      run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

    - name: Start ngrok
      run: ngrok http --domain=handy-labrador-humane.ngrok-free.app 5000 &

    - name: Run script.py
      run: python script.py
      env:
        CURRENT_RUN_ID: ${{ github.run_id }}
        PREVIOUS_RUN_ID: ${{ github.event.inputs.previous_run_id }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
