name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      previous_run_id:
        description: 'Enter the previous run ID'
        required: true

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any dependencies

    - name: Set environment variables
      run: echo "CURRENT_RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV

    - name: Run script.py
      run: python script.py
      env:
        PREVIOUS_RUN_ID: ${{ github.event.inputs.previous_run_id }}
        CURRENT_RUN_ID: ${{ env.CURRENT_RUN_ID }}
